linters:
  disable:
    - unused # Disables unreachable code checking

run:
  # Exclude test files from analysis
  tests: false

# Define which files and directories to exclude
issues:
  exclude-rules:
    # Exclude all test files
    - path: _test\.go
      linters:
        - all

  # Exclude specific directories
  exclude-dirs:
    - app
    - app/common
    - app/context
    - app/views
    - cmd/hway
    - handlers
    - internal

  # Exclude specific file patterns
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_templ\\.go$"
